/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MOTION_PB_H_INCLUDED
#define PB_MOTION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _HourlyResult {
    int64_t UnixTime;
    float AvgMinuteList[60];
} HourlyResult;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HourlyResult_init_default                {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define HourlyResult_init_zero                   {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define HourlyResult_UnixTime_tag                1
#define HourlyResult_AvgMinuteList_tag           2

/* Struct field encoding specification for nanopb */
#define HourlyResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    UnixTime,          1) \
X(a, STATIC,   FIXARRAY, FLOAT,    AvgMinuteList,     2)
#define HourlyResult_CALLBACK NULL
#define HourlyResult_DEFAULT NULL

extern const pb_msgdesc_t HourlyResult_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HourlyResult_fields &HourlyResult_msg

/* Maximum encoded size of messages (where known) */
#define HourlyResult_size                        311
#define MOTION_PB_H_MAX_SIZE                     HourlyResult_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
